// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmxKiR8pfg5cAbotvJZiKT7THS18Mekg4',
    appId: '1:857960187954:web:6c8fa334fa888f7395542b',
    messagingSenderId: '857960187954',
    projectId: 'flutterfire-ui-codelab-89add',
    authDomain: 'flutterfire-ui-codelab-89add.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-89add.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhaLfafARUwpOMzXaBkD06RkAVQyv8jEc',
    appId: '1:857960187954:android:d35319b2d3b596ac95542b',
    messagingSenderId: '857960187954',
    projectId: 'flutterfire-ui-codelab-89add',
    storageBucket: 'flutterfire-ui-codelab-89add.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkWWzxI88mgtPw0_D7OEHUKMdXJsaZJE4',
    appId: '1:857960187954:ios:c981b81461dd360d95542b',
    messagingSenderId: '857960187954',
    projectId: 'flutterfire-ui-codelab-89add',
    storageBucket: 'flutterfire-ui-codelab-89add.appspot.com',
    iosClientId: '857960187954-fvlpe4jvjibqs360jr8lf04fsangqi91.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkWWzxI88mgtPw0_D7OEHUKMdXJsaZJE4',
    appId: '1:857960187954:ios:c981b81461dd360d95542b',
    messagingSenderId: '857960187954',
    projectId: 'flutterfire-ui-codelab-89add',
    storageBucket: 'flutterfire-ui-codelab-89add.appspot.com',
    iosClientId: '857960187954-fvlpe4jvjibqs360jr8lf04fsangqi91.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
